name: CI
on: [push]
jobs:
      build:
        runs-on: macOS-latest

        steps:
        - name: Checkout
          uses: actions/checkout@master
      #- name: Testing....
      # run: ls /Applications | grep Xcode
        - name: iPhone 11 Test
          run: xcodebuild clean test -project GithubCIIntegration.xcodeproj -scheme GithubCIIntegration -destination "platform=iOS Simulator,name=iPhone 11 Pro"
