name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: macOS-latest
    steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Testing....
              run: sudo xcode-select -switch /Applications/Xcode_11.3.app
            - name: iPhone 11 Test
              run: xcodebuild test -scheme GithubCIIntegration -project GithubCIIntegration.xcodeproj -destination 'platform:iOS Simulator, id:733D6C75-B255-4B6D-9D47-D710FA0E4ACE, OS:13.3, name:iPhone 11 '
